reporters:
  - name: http ping
    module: "http"
    interval: 4 # time in seconds
    options:
      method: GET
      url: http://localhost:3000/v1/users
      timeout: 30000
      acceptableStatus:
        - 200
        - 201
      headers:
        apiKey: "apiKeyHere"

  - name: tile38
    module: "Tile38"
    interval: 5 # time in seconds
    options:
      url: http://localhost:9851
      timeout: 30 # time in seconds
      min: 20
  - name: tile38 shrink
    module: "http"
    interval: 50 # time in seconds
    options:
      method: POST
      url: http://localhost:9851/aofshrink
      acceptableStatus:
        - 200
